replicaCount: 1

namespace: products-platform   # 🔥 your namespace

image:
  repository: eureka-server
  tag: "101"
  pullPolicy: Never

service:
  type: NodePort
  port: 8761
  targetPort: 8761
  nodePort: 30061

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi